### ISSUE TITLE
Build on Windows, help!

### ISSUE THREAD

**Issue by meruune** [codeplaysoftware/tensorflow#26]
Hello!

I have some question.
(None errors, vega64, i7 7500, second pc lower)

I know that ROCm is not supported on windows, but opencl is.
So, can i know if there is any way to build your tensorflow, on windows?
If not, is there any way to build it with cmake, including sycl?

I saw some people built on windows older tensorflow-cmake project.
Sorry that there are only questions, but i just wanted to ask.

Thank you!

**Comment by rodburns** [comment]
We don't build or test our TensorFlow branch with Windows at the moment. It may be possible but we have not tried it, and you would need to find the correct version of the AMD drivers that supports SPIR since SPIR or SPIR-V is required for our SYCL implementation to work. (see [this thread](https://community.amd.com/thread/232093) for background)
I can't offer any guarantees about it working.

**Comment by Rbiessy** [comment]
Questions have been answered so closing thread. Feel free to re-open if we can provide any more help.
